name:                straight-line
version:             0.1.0
github:              "kmein/straight-line"
license:             MIT
author:              "Kierán Meinhardt"
maintainer:          "kieran.meinhardt@gmail.com"
copyright:           "Copyright (c) 2018 Kierán Meinhardt"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/kmein/straight-line#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- parsers
- wl-pprint
- QuickCheck

library:
  source-dirs: src

executables:
  slc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - straight-line
    - optparse-applicative
    - parsec

tests:
  slc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsec
    - straight-line
    - tasty
    - tasty-hunit
    - tasty-quickcheck
